version: '3'

services:

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=logsdb
    ports:
      - "5432:5432"
    networks:
      - postgres
    volumes:
      - pg_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - "5672:5672" 
      - "15672:15672"
      - "15693:15692"
      - "5552:5552"
    networks:
      - postgres
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
  

networks:
  postgres:
    driver: bridge


volumes:
  pg_data:
